#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "denite"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
name = "tmux"

[[layers]]
name = "lang#typescript"

[[custom_plugins]]
name = "mustache/vim-mustache-handlebars"

[[custom_plugins]]
name = "Quramy/vim-js-pretty-template"

[[custom_plugins]]
name = "tmux-plugins/vim-tmux-focus-events"

[[custom_plugins]]
name = "tpope/vim-obsession"

[[custom_plugins]]
name ="janko-m/vim-test"
